language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1

cache:
  directories:
  - $HOME/.composer/cache

service:
  - memcached
  - redis-server
  - mysql

before_script:
  - composer install
  - composer dump-autoload
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan vendor:publish --tag=0
  - mysql -e 'CREATE DATABASE IF NOT EXISTS laravel_plus ;'
  - php artisan migrate

script: phpunit
